name: Integration Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10.13', '3.11.5' ]

    env:
      POETRY_NO_INTERACTION: 1
      PIP_DEFAULT_TIMEOUT: 100  

    steps:
      - name: Set up Python & Poetry
        uses: sensodevices/async-sendgrid/.github/actions/build_async_sendgrid
        with:
          poetry-version: '1.6.1'
          python-version: ${{ matrix.python-version }}

      - name: Execute Pytest
        run: poetry run python -m pytest --cov=async-sendgrid tests/integration